import psycopg2
from psycopg2.extras import RealDictCursor
from config import DATABASE_URL
import logging

def get_conn():
    """Establish a connection to the PostgreSQL database."""
    conn = psycopg2.connect(DATABASE_URL)
    return conn

def init_db():
    """Initialize the PostgreSQL database with necessary tables."""
    conn = get_conn()
    cur = conn.cursor()
    
    # Users table
    cur.execute('''
        CREATE TABLE IF NOT EXISTS users (
            user_id BIGINT PRIMARY KEY,
            is_premium BOOLEAN DEFAULT FALSE,
            language TEXT,
            full_name TEXT,
            username TEXT
        )
    ''')
    
    # Pending Transactions table
    cur.execute('''
        CREATE TABLE IF NOT EXISTS pending_transactions (
            user_id BIGINT,
            comment_id TEXT PRIMARY KEY,
            amount INTEGER,
            status TEXT DEFAULT 'pending'
        )
    ''')
    
    # Generations table
    cur.execute('''
        CREATE TABLE IF NOT EXISTS generations (
            id SERIAL PRIMARY KEY,
            user_id BIGINT,
            prompt TEXT,
            enhanced_prompt TEXT,
            image_url TEXT,
            is_public BOOLEAN DEFAULT FALSE,
            timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    
    conn.commit()
    cur.close()
    conn.close()

def add_user(user_id, full_name=None, username=None):
    """Add or update a user in the database."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute('''
        INSERT INTO users (user_id, full_name, username) VALUES (%s, %s, %s)
        ON CONFLICT (user_id) DO UPDATE SET 
            full_name = COALESCE(EXCLUDED.full_name, users.full_name),
            username = COALESCE(EXCLUDED.username, users.username)
    ''', (user_id, full_name, username))
    conn.commit()
    cur.close()
    conn.close()

def set_user_language(user_id, lang):
    """Set user's language preference."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("UPDATE users SET language = %s WHERE user_id = %s", (lang, user_id))
    conn.commit()
    cur.close()
    conn.close()

def get_user_language(user_id):
    """Get user's language preference."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT language FROM users WHERE user_id = %s", (user_id,))
    res = cur.fetchone()
    cur.close()
    conn.close()
    return res[0] if res else None

def set_premium(user_id, status=True):
    """Set the premium status for a user."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("UPDATE users SET is_premium = %s WHERE user_id = %s", (status, user_id))
    conn.commit()
    cur.close()
    conn.close()

def is_premium(user_id):
    """Check if a user has premium status."""
    # Admin Overrides
    if user_id == 6437879950: 
        return True
    
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT is_premium FROM users WHERE user_id = %s", (user_id,))
    res = cur.fetchone()
    cur.close()
    conn.close()
    return bool(res[0]) if res else False

def create_transaction(user_id, comment_id, amount):
    """Store a pending payment."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("INSERT INTO pending_transactions (user_id, comment_id, amount) VALUES (%s, %s, %s)", 
                (user_id, comment_id, amount))
    conn.commit()
    cur.close()
    conn.close()

def get_transaction_by_comment(comment_id):
    """Retrieve transaction details by comment ID."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT user_id, amount, status FROM pending_transactions WHERE comment_id = %s", (comment_id,))
    res = cur.fetchone()
    cur.close()
    conn.close()
    return res 

def mark_transaction_paid(comment_id):
    """Update transaction status and grant premium."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT user_id FROM pending_transactions WHERE comment_id = %s", (comment_id,))
    res = cur.fetchone()
    if res:
        user_id = res[0]
        cur.execute("UPDATE pending_transactions SET status = 'paid' WHERE comment_id = %s", (comment_id,))
        cur.execute("UPDATE users SET is_premium = true WHERE user_id = %s", (user_id,))
        conn.commit()
        cur.close()
        conn.close()
        return user_id
    cur.close()
    conn.close()
    return None

def save_generation(user_id, prompt, enhanced_prompt, image_url):
    """Save a generated image to the database."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("INSERT INTO generations (user_id, prompt, enhanced_prompt, image_url) VALUES (%s, %s, %s, %s)",
                (user_id, prompt, enhanced_prompt, image_url))
    conn.commit()
    cur.close()
    conn.close()

def get_user_generations(user_id):
    """Retrieve all images generated by a specific user."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("SELECT prompt, image_url, timestamp, is_public, id FROM generations WHERE user_id = %s ORDER BY timestamp DESC", (user_id,))
    res = cur.fetchall()
    cur.close()
    conn.close()
    return res

def set_generation_public(gen_id, is_public=True):
    """Toggle the public visibility of a generation."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute("UPDATE generations SET is_public = %s WHERE id = %s", (is_public, gen_id))
    conn.commit()
    cur.close()
    conn.close()

def get_public_generations():
    """Retrieve all public images from all users."""
    conn = get_conn()
    cur = conn.cursor()
    cur.execute('''
        SELECT g.prompt, g.image_url, g.timestamp, u.full_name, u.username 
        FROM generations g
        JOIN users u ON g.user_id = u.user_id
        WHERE g.is_public = true
        ORDER BY g.timestamp DESC
    ''')
    res = cur.fetchall()
    cur.close()
    conn.close()
    return res
