LOCALIZED_STRINGS = {
    "uz": {
        "welcome": "Xush kelibsiz",
        "desc": "Siz raqamli nafislik dunyosiga kirdingiz. Men sizning maxsus AI yordamchingizman.",
        "create": "🎨 *Tasvir yaratish:* Tasvir yaratish uchun `/image` buyrug'idan so'ng tavsifni yuboring.",
        "premium": "💎 *Premium kirish:* `/buy` buyrug'i orqali tezkor tasvir yaratishni faollashtiring.",
        "buy_prompt": "Premium tajriba uchun afzal to'lov tizimini tanlang:",
        "manual_info": "🏦 *Uzcard / Humo o'tkazmasi*\n\nIltimos, roppa-rosa *{amount:,} UZS* o'tkazing:\n`{card}`\n\n⚠️ *MUHIM:* O'tkazma izohida ushbu kodni ko'rsatish shart:\n`{comment}`\n\nTo'lov aniqlangach, premium status 10-60 soniyada avtomatik faollashadi.",
        "imagine_prompt": "Iltimos, tavsif kiriting! Misol: `/image Kelajak ish stoli...`",
        "orchestrating": "🎨 Vizual asaringiz tayyorlanmoqda. Iltimos, kuting...",
        "premium_wait": "✨ *Premium ustuvorlik:* Vizual asaringiz tezlashtirilgan tartibda tayyorlanmoqda. Taxminiy vaqt: 15 soniya.",
        "standard_wait": "🎨 *Standart daraja:* Sizning vizual asaringiz tayyorlanmoqda. Bepul a'zo sifatida siz standart navbatdasiz (taxminan 2.5 daqiqa).\n\n💡 *Eslatma:* 15 soniyada yaratish uchun /buy orqali yangilang.",
        "error": "Nafis uzilish yuz berdi. Iltimos, qaytadan urinib ko'ring.",
        "vision_premium": "Vizual tahlil - bu bizning premium xizmatimiz. Iltimos, /buy orqali darajangizni oshiring.",
        "vision_processing": "Vizual elementlaringiz aniqlik bilan qayta ishlanmoqda...",
        "director_mode": "✨ *Rejissyor rejimi:* Tasviringizni eng yuqori sifatli va professional darajaga ko'tarish uchun tayyorlanmoqda...",
        "progress_prefix": "🎨 Tasvir tayyorlanmoqda:",
        "publish": "Kanalga joylash 📤",
        "add_to_gallery": "Galereyaga Qo'shish 📥",
        "view_gallery": "Mening Galereyam 🖼️",
        "support": "Qo'llab-quvvatlash 👨‍💻",
        "menu_gallery": "🖼️ Galereya",
        "menu_buy": "💎 Premium",
        "support_msg": "✨ *LuxeSupport:* Savollaringiz yoki muammolaringiz bormi? Bizning qo'llab-quvvatlash jamoamiz sizga yordam berishga tayyor: @vm\\_aziz",
        "menu_create": "🎨 Tasvir yaratish",
        "prompt_request": "Iltimos, tavsifingizni yuboring. Agar g'oyangiz bo'lmasa, 'G'oya' tugmasini bosing.",
        "idea_button": "💡 G'oya",
        "idea_request": "Qanday tasvir yaratmoqchisiz? O'z so'zlaringiz bilan tasvirlab bering.",
        "refined_vision": "✨ *Sizning nafis g'oyangiz:*",
        "send_to_bot": "Botga yuborish! 🚀",
        "thinking": "✨ *LuxeAI o'ylamoqda:* G'oyangizni nafislashtirmoqda...",
        "manual_visa_info": "💳 *Visa / Mastercard Transfer*\n\nPlease transfer *${amount} USD* to:\n`{card}`\n\n⚠️ *IMPORTANT:* Send a screenshot of the payment to @vm_aziz to activate premium.",
        "choose_method": "Qanday usulda asar yaratmoqchisiz?",
        "method_ref": "Rasm orqali 🖼️",
        "method_idea": "G'oya orqali 💡",
        "ref_req": "Iltimos, rasm yuboring. Unga tavsif ham qo'shishingiz mumkin."
    },
    "ru": {
        "welcome": "Добро пожаловать",
        "desc": "Вы вошли в мир цифровой изысканности. Я ваш персональный ИИ-ассистент.",
        "create": "🎨 *Создание изображений:* Чтобы создать изображение, отправьте `/image` и описание.",
        "premium": "💎 *Premium доступ:* Используйте `/buy` для мгновенной генерации за 15 секунд.",
        "buy_prompt": "Выберите предпочтительную платежную систему для Premium доступа:",
        "manual_info": "🏦 *Перевод Uzcard / Humo*\n\nПожалуйста, переведите ровно *{amount:,} UZS* на:\n`{card}`\n\n⚠️ *ВАЖНО:* Вы ОБЯЗАТЕЛЬНО должны указать этот код в комментарии к переводу:\n`{comment}`\n\nКак только система обнаружит перевод, статус будет активирован автоматически через 10-60 секунд.",
        "imagine_prompt": "Пожалуйста, введите описание! Пример: `/image Футуристичное рабочее место...`",
        "orchestrating": "🎨 Ваш визуальный шедевр создается. Пожалуйста, подождите...",
        "premium_wait": "✨ *Premium приоритет:* Ваш визуальный шедевр создается в ускоренном режиме. Ожидаемое время: 15 секунд.",
        "standard_wait": "🎨 *Стандартный уровень:* Ваш шедевр создается. Как бесплатный пользователь, вы находитесь в стандартной очереди (около 2.5 минут).\n\n💡 *Примечание:* Используйте /buy для генерации за 15 секунд.",
        "error": "Произошел элегантный сбой. Пожалуйста, попробуйте еще раз.",
        "vision_premium": "Визуальный анализ — это премиум-услуга. Пожалуйста, используйте /buy для повышения статуса.",
        "vision_processing": "Ваши визуальные элементы обрабатываются с изысканной точностью...",
        "director_mode": "✨ *Режим режиссера:* Улучшение вашего запроса до профессионального уровня 8K...",
        "progress_prefix": "🎨 Создание изображения:",
        "publish": "Опубликовать в канал 📤",
        "add_to_gallery": "Добавить в галерею 📥",
        "view_gallery": "Моя Галерея 🖼️",
        "support": "Поддержка 👨‍💻",
        "menu_gallery": "🖼️ Галерея",
        "menu_buy": "💎 Premium",
        "support_msg": "✨ *LuxeSupport:* У вас есть вопросы или возникли проблемы? Наша служба поддержки готова помочь: @vm\_aziz",
        "menu_create": "🎨 Создать изображение",
        "prompt_request": "Пожалуйста, отправьте ваш запрос. Если у вас нет идей, нажмите кнопку 'Идея'.",
        "idea_button": "💡 Идея",
        "idea_request": "Какое изображение вы хотите создать? Опишите своими словами.",
        "refined_vision": "✨ *Ваше изысканное видение:*",
        "send_to_bot": "Отправить боту! 🚀",
        "thinking": "✨ *LuxeAI думает:* Совершенствуем вашу идею...",
        "manual_visa_info": "💳 *Перевод Visa / Mastercard*\n\nПожалуйста, переведите *${amount} USD* на:\n`{card}`\n\n⚠️ *ВАЖНО:* Отправьте скриншот оплаты @vm_aziz для активации.",
        "choose_method": "Как вы хотите создать шедевр?",
        "method_ref": "Через фото 🖼️",
        "method_idea": "Через идею 💡",
        "ref_req": "Пожалуйста, отправьте фото. Вы также можете добавить описание."
    },
    "en": {
        "welcome": "Welcome",
        "desc": "You have entered a world of digital refinement. I am your bespoke AI assistant.",
        "create": "🎨 *Visual Creation:* To create an image, send `/image` followed by your vision.",
        "premium": "💎 *Premium Access:* Use `/buy` for instant 15-second generation.",
        "buy_prompt": "Select your preferred payment gateway for the Premium experience:",
        "manual_info": "🏦 *Uzcard / Humo Transfer*\n\nPlease transfer exactly *{amount:,} UZS* to:\n`{card}`\n\n⚠️ *IMPORTANT:* You MUST include this comment in the transfer precisely:\n`{comment}`\n\nOnce our system detects the transfer, your premium status will be activated automatically in 10-60 seconds.",
        "imagine_prompt": "Please provide a description! Example: `/image A futuristic luxury workspace...`",
        "orchestrating": "🎨 Orchestrating your visual masterpiece. Please wait a moment...",
        "premium_wait": "✨ *Premium Priority Access:* Your visual masterpiece is being orchestrated with expedited precision. Estimated time: 15 seconds.",
        "standard_wait": "🎨 *Standard Tier:* Orchestrating your vision. As a free member, your request is in the standard queue (est. 2.5 minutes).\n\n💡 *Note:* Upgrade to /buy for instant 15-second generation.",
        "error": "An elegant interruption occurred. Please try again.",
        "vision_premium": "Visual analysis is a premier offering. Please use /buy to elevate your membership status.",
        "vision_processing": "Processing your visual elements with refined precision...",
        "director_mode": "✨ *Director Mode:* Refining your vision for ultra-high professional quality...",
        "progress_prefix": "🎨 Image creation in progress:",
        "publish": "Publish to Channel 📤",
        "add_to_gallery": "Add to Gallery 📥",
        "view_gallery": "My Gallery 🖼️",
        "support": "Support 👨‍💻",
        "menu_gallery": "🖼️ Gallery",
        "menu_buy": "💎 Premium",
        "support_msg": "✨ *LuxeSupport:* Have questions or encountered an issue? Our support team is ready to assist you: @vm\_aziz",
        "menu_create": "🎨 Create Image",
        "prompt_request": "Please send your prompt. If you don't have an idea, click the 'Idea' button.",
        "idea_button": "💡 Idea",
        "idea_request": "What kind of image do you want to generate? Describe it in your own words.",
        "refined_vision": "✨ *Your Refined Vision:*",
        "send_to_bot": "Send to Bot! 🚀",
        "thinking": "✨ *LuxeAI is thinking:* Refining your vision...",
        "manual_visa_info": "💳 *Visa / Mastercard Transfer*\n\nPlease transfer *${amount} USD* to:\n`{card}`\n\n⚠️ *IMPORTANT:* Send a screenshot of the payment to @vm_aziz to activate premium.",
        "choose_method": "How would you like to create your masterpiece?",
        "method_ref": "With Reference Photo 🖼️",
        "method_idea": "With Idea / Prompt 💡",
        "ref_req": "Please upload a photo. You can also add a caption with instructions."
    }
}
