LOCALIZED_STRINGS = {
    "uz": {
        "welcome": "Xush kelibsiz",
        "desc": "Siz raqamli nafislik dunyosiga kirdingiz. Men sizning maxsus AI yordamchingizman.",
        "create": "🎨 <b>Tasvir yaratish:</b> Tasvir yaratish uchun `/image` buyrug'idan so'ng tavsifni yuboring.",
        "premium": "💎 <b>Premium kirish:</b> `/buy` buyrug'i orqali tezkor tasvir yaratishni faollashtiring.",
        "buy_prompt": "Premium tajriba uchun afzal to'lov tizimini tanlang:",
        "manual_info": "🏦 <b>Uzcard / Humo o'tkazmasi</b>\n\nIltimos, roppa-rosa <b>{amount:,} UZS</b> o'tkazing:\n<code>{card}</code>\n\n⚠️ <b>MUHIM:</b> O'tkazma izohida ushbu kodni ko'rsatish shart:\n<code>{comment}</code>\n\nTo'lov aniqlangach, premium status 10-60 soniyada avtomatik faollashadi.",
        "imagine_prompt": "Iltimos, tavsif kiriting! Misol: `/image Kelajak ish stoli...`",
        "orchestrating": "🎨 Vizual asaringiz tayyorlanmoqda. Iltimos, kuting...",
        "premium_wait": "✨ <b>Premium ustuvorlik:</b> Vizual asaringiz tezlashtirilgan tartibda tayyorlanmoqda. Taxminiy vaqt: 15 soniya.",
        "standard_wait": "🎨 <b>Standart daraja:</b> Sizning vizual asaringiz tayyorlanmoqda. Bepul a'zo sifatida siz standart navbatdasiz (taxminan 2.5 daqiqa).\n\n💡 <b>Eslatma:</b> 15 soniyada yaratish uchun /buy orqali yangilang.",
        "error": "Nafis uzilish yuz berdi. Iltimos, qaytadan urinib ko'ring.",
        "vision_premium": "Vizual tahlil - bu bizning premium xizmatimiz. Iltimos, /buy orqali darajangizni oshiring.",
        "vision_processing": "Vizual elementlaringiz aniqlik bilan qayta ishlanmoqda...",
        "director_mode": "✨ <b>Rejissyor rejimi:</b> Tasviringizni eng yuqori sifatli va professional darajaga ko'tarish uchun tayyorlanmoqda...",
        "progress_prefix": "🎨 Tasvir tayyorlanmoqda:",
        "publish": "Kanalga joylash 📤",
        "add_to_gallery": "Galereyaga Qo'shish 📥",
        "view_gallery": "Mening Galereyam 🖼️",
        "support": "Qo'llab-quvvatlash 👨‍💻",
        "menu_gallery": "🖼️ Galereya",
        "menu_buy": "💎 Premium",
        "support_msg": "✨ <b>LuxeSupport:</b> Savollaringiz yoki muammolaringiz bormi? Bizning qo'llab-quvvatlash jamoamiz sizga yordam berishga tayyor: @vm_aziz",
        "menu_create": "🎨 Tasvir yaratish",
        "prompt_request": "Iltimos, tavsifingizni yuboring. Agar g'oyangiz bo'lmasa, 'G'oya' tugmasini bosing.",
        "idea_button": "💡 G'oya",
        "idea_request": "Qanday tasvir yaratmoqchisiz? O'z so'zlaringiz bilan tasvirlab bering.",
        "refined_vision": "✨ <b>Sizning nafis g'oyangiz:</b>",
        "send_to_bot": "Botga yuborish! 🚀",
        "thinking": "✨ <b>LuxeAI o'ylamoqda:</b> G'oyangizni nafislashtirmoqda...",
        "pay_uzb": "🇺🇿 Uzbekistan (Uzcard / Humo)",
        "pay_visa": "💳 Visa / Mastercard",
        "manual_visa_info": "💳 <b>Visa / Mastercard Transfer</b>\n\nIltimos, <b>${amount} USD</b> o'tkazing:\n<code>{card}</code>\n\n⚠️ <b>MUHIM:</b> To'lovni tasdiqlash uchun chekni @vm_aziz ga yuboring.",
        "choose_method": "Qanday usulda asar yaratmoqchisiz?",
        "method_ref": "Rasm orqali 🖼️",
        "method_idea": "G'oya orqali 💡",
        "ref_req": "Iltimos, rasm yuboring. Unga tavsif ham qo'shishingiz mumkin."
    },
    "ru": {
        "welcome": "Добро пожаловать",
        "desc": "Вы вошли в мир цифровой изысканности. Я ваш персональный ИИ-ассистент.",
        "create": "🎨 <b>Создание изображений:</b> Чтобы создать изображение, отправьте `/image` и описание.",
        "premium": "💎 <b>Premium доступ:</b> Используйте `/buy` для мгновенной генерации за 15 секунд.",
        "buy_prompt": "Выберите предпочтительную платежную систему для Premium доступа:",
        "manual_info": "🏦 <b>Перевод Uzcard / Humo</b>\n\nПожалуйста, переведите ровно <b>{amount:,} UZS</b> на:\n<code>{card}</code>\n\n⚠️ <b>ВАЖНО:</b> Вы ОБЯЗАТЕЛЬНО должны указать этот код в комментарии к переводу:\n<code>{comment}</code>\n\nКак только система обнаружит перевод, статус будет активирован автоматически через 10-60 секунд.",
        "imagine_prompt": "Пожалуйста, введите описание! Пример: `/image Футуристичное рабочее место...`",
        "orchestrating": "🎨 Ваш визуальный шедевр создается. Пожалуйста, подождите...",
        "premium_wait": "✨ <b>Premium приоритет:</b> Ваш визуальный шедевр создается в ускоренном режиме. Ожидаемое время: 15 секунд.",
        "standard_wait": "🎨 <b>Стандартный уровень:</b> Ваш шедевр создается. Как бесплатный пользователь, вы находитесь в стандартной очереди (около 2.5 минут).\n\n💡 <b>Примечание:</b> Используйте /buy для генерации за 15 секунд.",
        "error": "Произошел элегантный сбой. Пожалуйста, попробуйте еще раз.",
        "vision_premium": "Визуальный анализ — это премиум-услуга. Пожалуйста, используйте /buy для повышения статуса.",
        "vision_processing": "Ваши визуальные элементы обрабатываются с изысканной точностью...",
        "director_mode": "✨ <b>Режим режиссера:</b> Улучшение вашего запроса до профессионального уровня 8K...",
        "progress_prefix": "🎨 Создание изображения:",
        "publish": "Опубликовать в канал 📤",
        "add_to_gallery": "Добавить в галерею 📥",
        "view_gallery": "Моя Галерея 🖼️",
        "support": "Поддержка 👨‍💻",
        "menu_gallery": "🖼️ Галерея",
        "menu_buy": "💎 Premium",
        "support_msg": "✨ <b>LuxeSupport:</b> У вас есть вопросы или возникли проблемы? Наша служба поддержки готова помочь: @vm_aziz",
        "menu_create": "🎨 Создать изображение",
        "prompt_request": "Пожалуйста, отправьте ваш запрос. Если у вас нет идей, нажмите кнопку 'Идея'.",
        "idea_button": "💡 Идея",
        "idea_request": "Какое изображение вы хотите создать? Опишите своими словами.",
        "refined_vision": "✨ <b>Ваше изысканное видение:</b>",
        "send_to_bot": "Отправить боту! 🚀",
        "thinking": "✨ <b>LuxeAI думает:</b> Совершенствуем вашу идею...",
        "pay_uzb": "🇺🇿 Узбекистан (Uzcard / Humo)",
        "pay_visa": "💳 Visa / Mastercard",
        "manual_visa_info": "💳 <b>Перевод Visa / Mastercard</b>\n\nПожалуйста, переведите <b>${amount} USD</b> на:\n<code>{card}</code>\n\n⚠️ <b>ВАЖНО:</b> Отправьте скриншот оплаты @vm_aziz для активации.",
        "choose_method": "Как вы хотите создать шедевр?",
        "method_ref": "Через фото 🖼️",
        "method_idea": "Через идею 💡",
        "ref_req": "Пожалуйста, отправьте фото. Вы также можете добавить описание."
    },
    "en": {
        "welcome": "Welcome",
        "desc": "You have entered a world of digital refinement. I am your bespoke AI assistant.",
        "create": "🎨 <b>Visual Creation:</b> To create an image, send `/image` followed by your vision.",
        "premium": "💎 <b>Premium Access:</b> Use `/buy` for instant 15-second generation.",
        "buy_prompt": "Select your preferred payment gateway for the Premium experience:",
        "manual_info": "🏦 <b>Uzcard / Humo Transfer</b>\n\nPlease transfer exactly <b>{amount:,} UZS</b> to:\n<code>{card}</code>\n\n⚠️ <b>IMPORTANT:</b> You MUST include this comment in the transfer precisely:\n<code>{comment}</code>\n\nOnce our system detects the transfer, your premium status will be activated automatically in 10-60 seconds.",
        "imagine_prompt": "Please provide a description! Example: `/image A futuristic luxury workspace...`",
        "orchestrating": "🎨 Orchestrating your visual masterpiece. Please wait a moment...",
        "premium_wait": "✨ <b>Premium Priority Access:</b> Your visual masterpiece is being orchestrated with expedited precision. Estimated time: 15 seconds.",
        "standard_wait": "🎨 <b>Standard Tier:</b> Orchestrating your vision. As a free member, your request is in the standard queue (est. 2.5 minutes).\n\n💡 <b>Note:</b> Upgrade to /buy for instant 15-second generation.",
        "error": "An elegant interruption occurred. Please try again.",
        "vision_premium": "Visual analysis is a premier offering. Please use /buy to elevate your membership status.",
        "vision_processing": "Processing your visual elements with refined precision...",
        "director_mode": "✨ <b>Director Mode:</b> Refining your vision for ultra-high professional quality...",
        "progress_prefix": "🎨 Image creation in progress:",
        "publish": "Publish to Channel 📤",
        "add_to_gallery": "Add to Gallery 📥",
        "view_gallery": "My Gallery 🖼️",
        "support": "Support 👨‍💻",
        "menu_gallery": "🖼️ Gallery",
        "menu_buy": "💎 Premium",
        "support_msg": "✨ <b>LuxeSupport:</b> Have questions or encountered an issue? Our support team is ready to assist you: @vm_aziz",
        "menu_create": "🎨 Create Image",
        "prompt_request": "Please send your prompt. If you don't have an idea, click the 'Idea' button.",
        "idea_button": "💡 Idea",
        "idea_request": "What kind of image do you want to generate? Describe it in your own words.",
        "refined_vision": "✨ <b>Your Refined Vision:</b>",
        "send_to_bot": "Send to Bot! 🚀",
        "thinking": "✨ <b>LuxeAI is thinking:</b> Refining your vision...",
        "pay_uzb": "🇺🇿 Uzbekistan (Uzcard / Humo)",
        "pay_visa": "💳 Visa / Mastercard",
        "manual_visa_info": "💳 <b>Visa / Mastercard Transfer</b>\n\nPlease transfer <b>${amount} USD</b> to:\n<code>{card}</code>\n\n⚠️ <b>IMPORTANT:</b> Send a screenshot of the payment to @vm_aziz to activate premium.",
        "choose_method": "How would you like to create your masterpiece?",
        "method_ref": "With Reference Photo 🖼️",
        "method_idea": "With Idea / Prompt 💡",
        "ref_req": "Please upload a photo. You can also add a caption with instructions."
    }
}
